name: ESP32-S3 NAT Router CI Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install ESP-IDF
      run: |
        git clone --recursive https://github.com/espressif/esp-idf.git -b v5.2
        cd esp-idf
        ./install.sh esp32s3
        echo "source $PWD/export.sh" >> $GITHUB_ENV

    - name: Build firmware
      run: |
        source esp-idf/export.sh
        idf.py set-target esp32s3
        idf.py build

    - name: Package firmware
      run: |
        mkdir -p build_artifacts
        cp build/*.bin build_artifacts/
        zip -r esp32s3-nat-router.zip build_artifacts/

    - name: Upload firmware artifacts
      uses: actions/upload-artifact@v4
      with:
        name: esp32s3-nat-router
        path: esp32s3-nat-router.zip
        retention-days: 7
